const ActionTypes = {
  START_INITIALIZE: 'START_INITIALIZE',
  END_INITIALIZE: 'END_INITIALIZE',
  START_ROUTE_CHANGE: 'START_ROUTE_CHANGE',
  END_ROUTE_CHANGE: 'END_ROUTE_CHANGE',
}

export default ActionTypes
